print("Gene Information:")
print("================")
print("ENSG00000008083 = JARID2 (Jumonji, AT Rich Interactive Domain 2)")
print("  - Located 4,295 bp upstream of your variant")
print("  - Chromatin regulator gene")
print()
print("ENSG00000271888 = [lncRNA gene]") 
print("  - Located 2,149 bp downstream of your variant")
print()
print("Variant Type: Intergenic variant (between genes)")
print("Impact: MODIFIER (non-coding region)")
