name: Lab Alert Forwarding Pipeline

on:
  schedule:
    # Run every 5 minutes during business hours (6 AM - 8 PM EST)
    - cron: '*/5 11-23 * * 1-5'  # UTC time (EST + 5 hours)
  workflow_dispatch:  # Allow manual triggers
    inputs:
      environment:
        description: 'Environment to run in'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - development

env:
  NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
  TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
  POWERBI_MONITOR_PUSH_URL: ${{ secrets.POWERBI_MONITOR_PUSH_URL }}
  POWERBI_METRICS_PUSH_URL: ${{ secrets.POWERBI_METRICS_PUSH_URL }}
  NOTION_ALERTS_DB_ID: ${{ secrets.NOTION_ALERTS_DB_ID }}

jobs:
  forward-alerts:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create logs directory
      run: |
        if (-not (Test-Path "logs")) {
          New-Item -ItemType Directory -Path "logs" -Force
        }
        
    - name: Validate environment variables
      run: |
        if (-not $env:NOTION_API_TOKEN) {
          Write-Error "NOTION_API_TOKEN is not set"
          exit 1
        }
        if (-not $env:TEAMS_WEBHOOK_URL) {
          Write-Error "TEAMS_WEBHOOK_URL is not set"
          exit 1
        }
        if (-not $env:POWERBI_MONITOR_PUSH_URL) {
          Write-Error "POWERBI_MONITOR_PUSH_URL is not set"
          exit 1
        }
        Write-Host "Environment variables validated successfully"
        
    - name: Run alert forwarding script
      run: |
        .\scripts\lab_alert_forwarding_simple.ps1
      env:
        NOTION_API_TOKEN: ${{ env.NOTION_API_TOKEN }}
        TEAMS_WEBHOOK_URL: ${{ env.TEAMS_WEBHOOK_URL }}
        POWERBI_MONITOR_PUSH_URL: ${{ env.POWERBI_MONITOR_PUSH_URL }}
        POWERBI_METRICS_PUSH_URL: ${{ env.POWERBI_METRICS_PUSH_URL }}
        NOTION_ALERTS_DB_ID: ${{ env.NOTION_ALERTS_DB_ID }}
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lab-alert-logs-${{ github.run_number }}
        path: logs/
        retention-days: 30
        
    - name: Notify on failure
      if: failure()
      run: |
        $errorMessage = @{
          "@type" = "MessageCard"
          "@context" = "http://schema.org/extensions"
          "themeColor" = "FF0000"
          "summary" = "Lab Alert Pipeline Failed"
          "sections" = @(
            @{
              "activityTitle" = "❌ Lab Alert Pipeline Failed"
              "facts" = @(
                @{ "name" = "Workflow"; "value" = "${{ github.workflow }}" }
                @{ "name" = "Run ID"; "value" = "${{ github.run_id }}" }
                @{ "name" = "Time"; "value" = "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" }
                @{ "name" = "Environment"; "value" = "${{ github.event.inputs.environment || 'production' }}" }
              )
            }
          )
        }
        
        Invoke-RestMethod -Uri $env:TEAMS_WEBHOOK_URL -Method Post -Body ($errorMessage | ConvertTo-Json -Depth 10) -ContentType "application/json"
      env:
        TEAMS_WEBHOOK_URL: ${{ env.TEAMS_WEBHOOK_URL }}

  performance-monitoring:
    runs-on: windows-latest
    needs: forward-alerts
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        echo "No dependencies needed for simplified script"
        
    - name: Run performance monitoring
      run: |
        python scripts/notion_lab_automation_simple.py
      env:
        NOTION_API_TOKEN: ${{ env.NOTION_API_TOKEN }}
        TEAMS_WEBHOOK_URL: ${{ env.TEAMS_WEBHOOK_URL }}
        
    - name: Generate performance report
      run: |
        python scripts/generate_crisis_report.py
      env:
        NOTION_API_TOKEN: ${{ env.NOTION_API_TOKEN }}
        
    - name: Upload performance report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-report-${{ github.run_number }}
        path: reports/
        retention-days: 90

  dashboard-update:
    runs-on: ubuntu-latest
    needs: [forward-alerts, performance-monitoring]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g @notionhq/client
        
    - name: Update dashboard
      run: |
        node scripts/update_crisis_dashboard.js
      env:
        NOTION_API_TOKEN: ${{ env.NOTION_API_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DASHBOARD_DB_ID }}
        
    - name: Deploy dashboard
      run: |
        echo "Dashboard updated successfully"
        # Add deployment steps here if using a web service
